Add AlmaLinux support
osuosl-cookbooks/osl-repos pull request #16
Opened 2023-01-25 21:09 UTC by EMH333

Currently a draft b/c:
- No rspec tests
- `yum-almalinux` isn't out yet
- isn't tested for AlmaLinux 9

2023-01-27 00:12 UTC, ramereth requested changes
- Update logic in `osl-repos-test::disable` and `osl-repos-test::highavailability' so that it'll work on alma as well.

2023-01-30 19:29 UTC, ramereth requested changes

2023-01-30 19:29 UTC, ramereth commented on kitchen.yml
> +      - centos-stream-8
```suggestion
      - centos_stream-8
```

2023-01-30 19:29 UTC, ramereth commented on resources/alma.rb
> +    passthrough passthrough
This is generally bad practice and could make some debugging an issue later on. Please rename the variable to something else.

2023-02-02 19:38 UTC, ramereth commented on kitchen.yml
> +
Could you please remove the new line here and on line 27?

2023-02-02 19:50 UTC, ramereth approved these changes
Major bump please.

2023-02-02 19:52 UTC, EMH333 commented
!bump major ~

2023-02-02 19:52 UTC, merged

2023-02-02 19:52 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v3.0.0.  Have a nice day!